### PR TITLE
fix: Solve mips compilation problem

### PR DESCRIPTION
**Pull request by myk1343**
Solve mips compilation problem

Log: Solve mips compilation problem

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
