### PR TITLE
fix: Fixed the OCR recognition crash

### PR DESCRIPTION
**Pull request by pengfeixx**
Fixed the OCR recognition crash

Bug: https://pms.uniontech.com/bug-view-288669.html
Log: Fixed the OCR recognition crash

### CODE REVIEW

**Review by rb-union — APPROVED** [review]

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]

**Pull request merged**
